#include "resi/src/lib.rs.h"  // Generated by cxx
#include <iostream>

int main() {
    try {
        // Create likelihood object
        auto likelihood = create_likelihood(
            "data/desidr2/desidr2_mean.txt",
            "data/desidr2/desidr2_cov.txt"
    );

        // Test a few parameter values
        double h0rd = 10000.0;
        double omegam = 0.3;

        double logL = logl(*likelihood, h0rd, omegam);

        std::cout << "Log-likelihood for h0rd=" << h0rd
            << ", omegam=" << omegam
            << ": " << logL << std::endl;

        // Test another point
        logL = logl(*likelihood, 120.0, 0.25);
        std::cout << "Log-likelihood for h0rd=120.0, omegam=0.25: " << logL << std::endl;

    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << std::endl;
        return 1;
    }

    return 0;
}
